# Supported funding model platforms
github: [sujaykumarh]
# patreon: sujaykumarh
open_collective:
ko_fi: sujaykumarh
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
custom: ['https://buymeacoffee.com/sujaykumarh']
